# Generated by Django 2.1.7 on 2019-04-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='password',
            field=models.CharField(default='', max_length=6),
        ),
    ]
