# Generated by Django 2.1.7 on 2019-04-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_vendor', '0002_supplier_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='password',
        ),
    ]
