# Generated by Django 2.1.5 on 2019-05-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_vendor', '0004_supplier_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='geolocation',
            field=models.CharField(default='https://www.google.com/maps/dir///@15.0172605,76.3178081,7z', max_length=300),
        ),
    ]
