# Generated by Django 2.1.7 on 2019-04-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190331_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.Product', verbose_name='Product Id')),
            ],
        ),
    ]
