# Generated by Django 2.1.7 on 2019-04-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
    ]
