# Generated by Django 2.1.7 on 2019-04-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_vendor', '0004_supplier_password'),
        ('shop', '0011_auto_20190421_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shop_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop_vendor.Supplier', verbose_name='Supplier'),
        ),
    ]
