# Generated by Django 2.1.7 on 2019-04-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_vendor', '0004_supplier_password'),
        ('shop', '0012_orders_shop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.Category', verbose_name='Category')),
                ('shop_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop_vendor.Supplier', verbose_name='Supplier')),
            ],
        ),
    ]
