# Generated by Django 2.1.7 on 2019-04-24 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_vendor', '0004_supplier_password'),
        ('shop', '0015_auto_20190422_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='category',
            name='shop_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop_vendor.Supplier', verbose_name='Supplier'),
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
