# Generated by Django 2.1.7 on 2019-04-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20190424_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='shop_name',
        ),
    ]
