# Generated by Django 2.1.7 on 2019-04-25 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20190425_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shop_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shop_vendor.Supplier', verbose_name='Supplier'),
        ),
    ]
