# Generated by Django 2.1.7 on 2019-04-25 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20190425_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shop_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop_vendor.Supplier', verbose_name='Supplier'),
        ),
    ]
