# Generated by Django 2.1.7 on 2019-04-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20190430_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('mobile', models.CharField(default='', max_length=70)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('confirm', models.CharField(max_length=20)),
            ],
        ),
    ]
